/**
 * Meta Conversions API (CAPI) — server-side event firing.
 *
 * Each event sent here is deduplicated with its browser-side Pixel
 * twin via a shared `event_id` (UUID generated by the frontend at
 * fire time, included in the API payload that triggers this server
 * call). Without a matching event_id, the same conversion is counted
 * twice in Events Manager.
 *
 * Env vars consumed:
 *   META_PIXEL_ID           — '1866739047322363' (same as browser)
 *   META_CAPI_ACCESS_TOKEN  — long EAA… token from Events Manager
 *   META_TEST_EVENT_CODE    — optional 'TEST...' string for Test Events tab
 *
 * If META_CAPI_ACCESS_TOKEN is empty/unset, sendEvent() silently
 * no-ops — safe to leave configured even before secrets are pasted.
 */

const crypto = require('crypto');

const PIXEL_ID = process.env.META_PIXEL_ID || '1866739047322363';
const TOKEN    = process.env.META_CAPI_ACCESS_TOKEN || '';
const TEST_CODE = process.env.META_TEST_EVENT_CODE || '';
const GRAPH_VERSION = 'v18.0';
const ENABLED = !!TOKEN;

// Boot-time diagnostic so we can see in Render logs whether CAPI
// is wired correctly. Doesn't print the token itself, only length.
console.log('[metaCapi] init', {
  enabled: ENABLED,
  pixelId: PIXEL_ID,
  tokenLength: TOKEN.length,
  testEventCode: TEST_CODE || '(none — events go LIVE)',
});

/** SHA-256 of a normalized string. Returns null for blanks. */
function sha256(s) {
  if (!s) return null;
  return crypto.createHash('sha256').update(String(s).trim().toLowerCase()).digest('hex');
}

/** Phone normalization for Meta: digits only, including country code. */
function normalizePhone(raw, defaultCountry = '91') {
  if (!raw) return null;
  const digits = String(raw).replace(/\D/g, '');
  if (!digits) return null;
  // Add country code if missing (10-digit Indian numbers only).
  if (digits.length === 10) return defaultCountry + digits;
  return digits;
}

/** Extract _fbp / _fbc cookies from a 'cookie' header string. */
function parseFbpFbc(cookieHeader) {
  if (!cookieHeader) return { fbp: null, fbc: null };
  const out = { fbp: null, fbc: null };
  for (const part of cookieHeader.split(';')) {
    const [k, ...rest] = part.trim().split('=');
    const v = rest.join('=');
    if (k === '_fbp') out.fbp = v;
    else if (k === '_fbc') out.fbc = v;
  }
  return out;
}

/**
 * Fire a single event to Meta CAPI.
 *
 * @param {object} opts
 * @param {string} opts.event_name        — e.g. 'Lead', 'CompleteRegistration', 'Schedule'
 * @param {string} opts.event_id          — UUID shared with the browser pixel (REQUIRED for dedup)
 * @param {string} [opts.event_source_url] — full URL where the action happened
 * @param {object} [opts.user_data]       — { email, phone, first_name, last_name, country, fbp, fbc, client_ip_address, client_user_agent }
 * @param {object} [opts.custom_data]     — { value, currency, content_name, content_category, ...whatever browser sent }
 */
async function sendEvent(opts) {
  if (!ENABLED) {
    console.warn('[metaCapi] SKIPPED — META_CAPI_ACCESS_TOKEN env var is not set on this server');
    return { sent: false, reason: 'no_token' };
  }

  const {
    event_name,
    event_id,
    event_source_url,
    user_data = {},
    custom_data = {},
  } = opts || {};

  if (!event_name) { console.warn('[metaCapi] SKIPPED — missing event_name'); return { sent: false, reason: 'missing_event_name' }; }
  if (!event_id)   { console.warn('[metaCapi] SKIPPED — missing event_id (frontend did not send meta_event_id)'); return { sent: false, reason: 'missing_event_id' }; }

  // Hash PII before transmission. Meta requires SHA-256 of normalized values.
  const ud = {};
  const emHash = sha256(user_data.email);
  const phHash = sha256(normalizePhone(user_data.phone));
  const fnHash = sha256(user_data.first_name);
  const lnHash = sha256(user_data.last_name);
  if (emHash) ud.em = [emHash];
  if (phHash) ud.ph = [phHash];
  if (fnHash) ud.fn = [fnHash];
  if (lnHash) ud.ln = [lnHash];
  if (user_data.country) ud.country = [sha256(user_data.country)];
  if (user_data.client_ip_address) ud.client_ip_address = user_data.client_ip_address;
  if (user_data.client_user_agent) ud.client_user_agent = user_data.client_user_agent;
  if (user_data.fbp) ud.fbp = user_data.fbp;
  if (user_data.fbc) ud.fbc = user_data.fbc;

  const payload = {
    data: [{
      event_name,
      event_time: Math.floor(Date.now() / 1000),
      event_id,
      action_source: 'website',
      event_source_url: event_source_url || undefined,
      user_data: ud,
      custom_data,
    }],
  };
  if (TEST_CODE) payload.test_event_code = TEST_CODE;

  const url = `https://graph.facebook.com/${GRAPH_VERSION}/${PIXEL_ID}/events?access_token=${encodeURIComponent(TOKEN)}`;

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    const body = await res.text();
    if (!res.ok) {
      console.error('[metaCapi]', event_name, 'failed:', res.status, body.slice(0, 300));
      return { sent: false, status: res.status, body: body.slice(0, 300) };
    }
    console.log('[metaCapi] ✓', event_name, 'event_id=' + event_id, 'value=' + (custom_data.value || 0), TEST_CODE ? '(TEST)' : '(LIVE)');
    return { sent: true, status: res.status };
  } catch (err) {
    console.error('[metaCapi]', event_name, 'network error:', err.message);
    return { sent: false, error: err.message };
  }
}

/** Convenience: extract everything we need from an Express req. */
function userDataFromReq(req, extras = {}) {
  const ip = (req.headers['x-forwarded-for'] || req.headers['x-real-ip'] || req.ip || '').split(',')[0].trim();
  const ua = req.headers['user-agent'] || '';
  const { fbp, fbc } = parseFbpFbc(req.headers.cookie);
  return {
    client_ip_address: ip || undefined,
    client_user_agent: ua || undefined,
    fbp: req.body?.fbp || fbp || undefined,
    fbc: req.body?.fbc || fbc || undefined,
    country: 'in',
    ...extras,
  };
}

module.exports = { sendEvent, userDataFromReq, parseFbpFbc };
